fluentd_version: 4
fluentd_package_state: present

fluentd_service_name: td-agent
fluentd_service_state: started
fluentd_service_enabled: true

fluentd_plugins:
  - fluent-plugin-elasticsearch
  - nginx
