FROM ubuntu:latest

#Update the package repository and install PostgreSQL
RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" TZ=Etc/UTC apt-get install -y postgresql

#Create a new PostgreSQL user and database
ARG USERNAME
ARG PASSWORD
ARG DBNAME

RUN service postgresql start && \
    su - postgres -c "psql -c \"CREATE USER $USERNAME WITH PASSWORD '$PASSWORD';\"" && \
    su - postgres -c "psql -c 'create database $DBNAME'" && \
    su - postgres -c "psql -c 'grant all privileges on database $DBNAME to $USERNAME;'"

#Configure PostgreSQL to allow connections from all IP addresses
RUN sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" /etc/postgresql/14/main/postgresql.conf && \
    echo "host all all 0.0.0.0/0 trust" >> /etc/postgresql/14/main/pg_hba.conf

#Expose the PostgreSQL default port
EXPOSE 5432

#Start the PostgreSQL service
CMD service postgresql start && tail -f /dev/null
